spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/shorturls
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  base64key: ${your_jwt_secret}
  expiration: 172800000 # 2days
